schema_version: 1

context:
  version: "0.30.4"

package:
  name: loop
  version: ${{ version }}

source:
  url: https://github.com/adrianliechti/loop/archive/v${{ version }}.tar.gz
  sha256: 2f94632c99585ec572e54e696fe923e35355bbc02c3a11ce84f251bef6035923

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - loop --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Seamless Development on Kubernetes
  homepage: https://github.com/adrianliechti/loop
  repository: https://github.com/adrianliechti/loop

extra:
  recipe-maintainers:
    - danielnachun
